parameters:
  configuration: ''
  testFramework: ''
  powerShellPlatform: ''

steps:
- template: download-build-steps.yml
  parameters:
    artifactName: build-${{ parameters.testFramework }}
- task: NodeTool@0
  condition: eq(variables.IsGenerateBased, true)
  displayName: Install autorest
  inputs:
    versionSpec: '14.17.1'
    command: custom
    verbose: false
    customCommand: install autorest@latest
- task: PowerShell@2
  condition: eq(variables.IsGenerateBased, true)
  displayName: Setup environment for autorest
  inputs:
    targetType: inline
    script: "$env:NODE_OPTIONS=\"--max-old-space-size=65536\""
    pwsh: true

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 6.0.x'
  inputs:
    packageType: sdk
    version: 6.0.x

- pwsh: 'Install-Module "platyPS", "PSScriptAnalyzer" -Force -Confirm:$false -Scope CurrentUser'
  displayName: 'Install PowerShell Dependencies'

- task: PowerShell@2
  displayName: 'Install latest modules'
  inputs:
    targetType: 'inline'
    script: |
      New-Item -ItemType Directory -Path "Az-Cmdlets-latest"
      Invoke-WebRequest -Uri "https://azpspackage.blob.core.windows.net/release/Az-Cmdlets-latest.tar.gz" -OutFile "Az-Cmdlets-latest/Az-Cmdlets-latest.tar.gz" -MaximumRetryCount 2 -RetryIntervalSec 1
      tar -xvzf "Az-Cmdlets-latest/Az-Cmdlets-latest.tar.gz" -C "Az-Cmdlets-latest"
      . Az-Cmdlets-latest/InstallModule.ps1
    pwsh: true
  
- task: DotNetCoreCLI@2
  displayName: 'Generate Help'
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:GenerateHelp /p:Configuration=${{ parameters.configuration }};PullRequestNumber=$(System.PullRequest.PullRequestNumber)'
  env:
      OCTOKITPAT: $(OCTOKITPAT)
      PowerShellPlatform: ${{ parameters.powerShellPlatform }}

- task: DotNetCoreCLI@2
  displayName: 'Static Analysis'
  inputs:
    command: custom
    custom: msbuild
    arguments: 'build.proj /t:StaticAnalysis /p:Configuration=${{ parameters.configuration }};PullRequestNumber=$(System.PullRequest.PullRequestNumber)'
  env:
      OCTOKITPAT: $(OCTOKITPAT)

- template: publish-artifacts-steps.yml
  parameters:
    artifactName: analyze-${{ parameters.testFramework }}
